src/Entity/SchoolYear.php
<?php

namespace App\Entity;

use App\Repository\SchoolYearRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SchoolYearRepository::class)
 */
class SchoolYear
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=190)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_end;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="school_year")
     */
    private $users;

    public function __construct()
    {
        $this->dateStart = new \DateTime();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(?\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(?\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setSchoolYear($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getSchoolYear() === $this) {
                $user->setSchoolYear(null);
            }
        }

        return $this;
    }
}

src/Form/SchoolYearType.php
<?php

namespace App\Form;

use App\Entity\SchoolYear;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SchoolYearType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('date_start')
            ->add('date_end')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SchoolYear::class,
        ]);
    }
}

src/Controller/SchoolYearController.php
<?php

namespace App\Controller;

use App\Entity\SchoolYear;
use App\Form\SchoolYearType;
use App\Repository\SchoolYearRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/schoolyear")
 */
class SchoolYearController extends AbstractController
{
    /**
     * @Route("/", name="school_year_index", methods={"GET"})
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_TEACHER')")
     */
    public function index(SchoolYearRepository $schoolYearRepository): Response
    {
        return $this->render('school_year/index.html.twig', [
            'school_years' => $schoolYearRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="school_year_new", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request): Response
    {
        $schoolYear = new SchoolYear();
        $form = $this->createForm(SchoolYearType::class, $schoolYear);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($schoolYear);
            $entityManager->flush();

            return $this->redirectToRoute('school_year_index');
        }

        return $this->render('school_year/new.html.twig', [
            'school_year' => $schoolYear,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="school_year_show", methods={"GET"})
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_STUDENT')")
     */
    public function show(SchoolYear $schoolYear): Response
    {
        return $this->render('school_year/show.html.twig', [
            'school_year' => $schoolYear,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="school_year_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, SchoolYear $schoolYear): Response
    {
        $form = $this->createForm(SchoolYearType::class, $schoolYear);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('school_year_index');
        }

        return $this->render('school_year/edit.html.twig', [
            'school_year' => $schoolYear,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="school_year_delete", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, SchoolYear $schoolYear): Response
    {
        if ($this->isCsrfTokenValid('delete'.$schoolYear->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($schoolYear);
            $entityManager->flush();
        }

        return $this->redirectToRoute('school_year_index');
    }
}

templates/school_year/_delete_form.html.twig
<form method="post" action="{{ path('school_year_delete', {'id': school_year.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ school_year.id) }}">
    <button class="btn">Delete</button>
</form>

templates/school_year/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/school_year/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit SchoolYear{% endblock %}

{% block body %}
    <h1>Edit SchoolYear</h1>

    {{ include('school_year/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('school_year_index') }}">back to list</a>

    {{ include('school_year/_delete_form.html.twig') }}
{% endblock %}

templates/school_year/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SchoolYear index{% endblock %}

{% block body %}
    <h1>SchoolYear index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Date_start</th>
                <th>Date_end</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for school_year in school_years %}
            <tr>
                <td>{{ school_year.id }}</td>
                <td>{{ school_year.name }}</td>
                <td>{{ school_year.dateStart ? school_year.dateStart|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ school_year.dateEnd ? school_year.dateEnd|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('school_year_show', {'id': school_year.id}) }}">show</a>
                    <a href="{{ path('school_year_edit', {'id': school_year.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('school_year_new') }}">Create new</a>
{% endblock %}

templates/school_year/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New SchoolYear{% endblock %}

{% block body %}
    <h1>Create new SchoolYear</h1>

    {{ include('school_year/_form.html.twig') }}

    <a href="{{ path('school_year_index') }}">back to list</a>
{% endblock %}

templates/school_year/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SchoolYear{% endblock %}

{% block body %}
    <h1>SchoolYear</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ school_year.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ school_year.name }}</td>
            </tr>
            <tr>
                <th>Date_start</th>
                <td>{{ school_year.dateStart ? school_year.dateStart|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_end</th>
                <td>{{ school_year.dateEnd ? school_year.dateEnd|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('school_year_index') }}">back to list</a>

    <a href="{{ path('school_year_edit', {'id': school_year.id}) }}">edit</a>

    {{ include('school_year/_delete_form.html.twig') }}
{% endblock %}